# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\backupProjects\HK_USB_Cam\ui/test.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        # MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(1136, 869)


        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)

        # self.label.setGeometry(QtCore.QRect(20, 40, 851, 721))
        self.label.setGeometry(QtCore.QRect(20, 40, 851, 721))

        self.label.setObjectName("label")
        # self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        # self.pushButton.setGeometry(QtCore.QRect(930, 690, 191, 101))
        # self.pushButton.setObjectName("pushButton")

        # MainWindow.setCentralWidget(self.centralwidget)

        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 1136, 23))
        # self.menubar.setObjectName("menubar")

        # MainWindow.setMenuBar(self.menubar)

        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")

        # MainWindow.setStatusBar(self.statusbar)

        # self.retranslateUi(MainWindow)

        """
        QtCore.QMetaObject.connectSlotsByName(MainWindow) 是一个用于自动连接信号和槽的函数。它通常在使用 Qt Designer 创建的窗口类中的构造函数中调用。

当你使用 Qt Designer 创建窗口界面时，可以给窗口中的小部件（如按钮、复选框等）命名。connectSlotsByName() 函数会根据小部件的命名和窗口类中的槽函数的命名自动连接对应的信号和槽。

例如，如果你在窗口中有一个名为 button_clicked 的按钮，并且窗口类中有一个名为 on_button_clicked 的槽函数，connectSlotsByName() 函数会自动将按钮的 clicked 信号与槽函数进行连接，这样当按钮被点击时，槽函数会自动被调用。

这种自动连接的方式使得在使用 Qt Designer 创建的窗口类中，你不需要显式编写连接代码，而是通过命名约定来自动建立信号和槽之间的连接，简化了代码的编写和维护。

需要注意的是，connectSlotsByName() 函数需要使用 QtCore.QObject 的元对象系统（Meta-Object System）来查找信号和槽。因此，你需要确保窗口类继承自 QtCore.QObject。
        """

        # QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # def retranslateUi(self, MainWindow):
    #     _translate = QtCore.QCoreApplication.translate
    #     MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
    #     self.label.setText(_translate("MainWindow", "TextLabel"))
    #     self.pushButton.setText(_translate("MainWindow", "PushButton"))
